CREATE TABLE "app"."account_balances" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."account_balances_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" integer,
	"balance" numeric(15, 2) DEFAULT '0' NOT NULL,
	"create_at" timestamp with time zone DEFAULT now(),
	"update_at" timestamp with time zone,
	CONSTRAINT "account_balances_unq_account_id" UNIQUE("account_id")
);
--> statement-breakpoint
ALTER TABLE "app"."account_balances" ADD CONSTRAINT "account_balances_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "app"."accounts"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "account_balances_idx_account_id" ON "app"."account_balances" USING btree ("account_id","id");