CREATE SCHEMA "app";
--> statement-breakpoint
CREATE SCHEMA "config";
--> statement-breakpoint
CREATE TYPE "public"."type" AS ENUM('fiat', 'crypto');--> statement-breakpoint
CREATE TABLE "app"."accounts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."accounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"type" "type",
	"currency_id" integer NOT NULL,
	"country_id" integer,
	"create_at" timestamp with time zone DEFAULT now(),
	"update_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "config"."countries" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "config"."countries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"code" varchar(3) NOT NULL,
	"default_currency_id" integer,
	"create_at" timestamp with time zone DEFAULT now(),
	"update_at" timestamp with time zone,
	CONSTRAINT "countries_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "config"."currencies" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "config"."currencies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" "type" NOT NULL,
	"name" varchar(255) NOT NULL,
	"code" varchar(3) NOT NULL,
	"symbol" varchar(10) NOT NULL,
	"symbol_native" varchar(10) NOT NULL,
	"create_at" timestamp with time zone DEFAULT now(),
	"update_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "config"."default_currency_lookup" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "config"."default_currency_lookup_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"country_code" varchar(3) NOT NULL,
	"currency_code" varchar(3) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"create_at" timestamp with time zone DEFAULT now(),
	"update_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "app"."accounts" ADD CONSTRAINT "accounts_currency_id_currencies_id_fk" FOREIGN KEY ("currency_id") REFERENCES "config"."currencies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."accounts" ADD CONSTRAINT "accounts_country_id_countries_id_fk" FOREIGN KEY ("country_id") REFERENCES "config"."countries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "config"."countries" ADD CONSTRAINT "countries_default_currency_id_currencies_id_fk" FOREIGN KEY ("default_currency_id") REFERENCES "config"."currencies"("id") ON DELETE no action ON UPDATE no action;