-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "schema_definitions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "schema_definitions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"version" varchar NOT NULL,
	"sql_content" text NOT NULL,
	"prev_id" bigint NOT NULL,
	"create_at" timestamp with time zone NOT NULL,
	"update_at" timestamp with time zone,
	CONSTRAINT "schema_definitions_version_key" UNIQUE("version"),
	CONSTRAINT "schema_definitions_prev_id_key" UNIQUE("prev_id")
);
--> statement-breakpoint
ALTER TABLE "schema_definitions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "forex" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "forex_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"date" date NOT NULL,
	"base_currency" varchar NOT NULL,
	"target_currency" varchar NOT NULL,
	"rate" numeric NOT NULL,
	"create_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "forex" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "Enable delete" ON "forex" AS PERMISSIVE FOR DELETE TO "dondondon_crud" USING (true);--> statement-breakpoint
CREATE POLICY "Enable update" ON "forex" AS PERMISSIVE FOR UPDATE TO "dondondon_crud";--> statement-breakpoint
CREATE POLICY "Enable insert" ON "forex" AS PERMISSIVE FOR INSERT TO "dondondon_crud";--> statement-breakpoint
CREATE POLICY "Enable read access" ON "forex" AS PERMISSIVE FOR SELECT TO "dondondon_readonly";
*/